name: 'Checkout Repositories'

runs:
  using: "composite"

  steps:
    - name: Checkout API repo
      uses: actions/checkout@v2
      with:
        path: orm
    - name: Checkout CartoCSS repo
      uses: actions/checkout@v2
      with:
        repository: OpenRailwayMap/OpenRailwayMap-CartoCSS
        path: CartoCSS
    - name: Checkout server-admin repo
      uses: actions/checkout@v2
      with:
        repository: OpenRailwayMap/server-admin
        path: server-admin
