name: 'Run API'

runs:
  using: "composite"

  steps:
    - name: Install NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '10'

    - name: Install npm deps
      working-directory: orm/api
      run: |
        npm install
      shell: bash

    - name: Start API service and fetch results
      working-directory: orm/api
      run: |
        npm run start &
        sleep 3
        curl -o ../../tests/actual/1.json 'http://localhost:9002/facility?name=Feldmoching'
      shell: bash

    - name: Grab actual JSON results as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: API output
        path:
          - tests/actual/
          - tests/known_good/
