name: CI

on: [ push, pull_request ]

jobs:
  test:
    services:
      postgres:
        image: kartoza/postgis:11.5-2.5
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: openrailwaymap
          POSTGRES_PASSWORD: gis_password
          POSTGRES_DB: gis
          POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,postgis_topology
          DEFAULT_ENCODING: 'UTF8'
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    runs-on: ubuntu-18.04

    steps:
      - uses: ./.github/actions/checkout
      - uses: ./.github/actions/prepare-database
      - uses: ./.github/actions/run-API
